# vim:fileencoding=utf-8:foldmethod=marker
#: -----------------------------------------
#: Overview of customization for kitty.conf
#: https://sw.kovidgoyal.net/kitty/overview/
#: https://sw.kovidgoyal.net/kitty/conf/
#: -----------------------------------------


#: Themes ------------------------- {{{
# Catppuccin-Macchiato
include themes/catppuccin-macchiato.conf
#: -------------------------------- }}}

#: Fonts -------------------------- {{{
font_family 		    JetBrainsMono Nerd Font
bold_font 		      JetBrainsMono Nerd Font Bold
italic_font 		    JetBrainsMono Nerd Font Italic
bold_italic_font 	  JetBrainsMono Nerd Font Bold Italic
font_size           12.0
#: -------------------------------- }}}

#: Text cursor -------------------- {{{
cursor_beam_thickness         1
cursor_underline_thickness    1
cursor_trail                  2
cursor_blink_interval         -1 ease-in-out
cursor_trail_color            #f0c6c6
#: -------------------------------- }}}

#: Scrollback --------------------- {{{
scrollbar_hitbox_expansion    1
#: -------------------------------- }}}

#: Mouse -------------------------- {{{
mouse_hide_wait           2.0
url_style                 straight
detect_urls               yes
show_hyperlink_targets    yes
underline_hyperlinks      hover
strip_trailing_spaces     smart
focus_follows_mouse       no
#: -------------------------------- }}}

#: Performance tuning ------------- {{{
# repaint_delay     10
# input_delay       3
sync_to_monitor   no
#: -------------------------------- }}}

#: Terminal bell ------------------ {{{
enable_audio_bell   no
bell_on_tab         " "
# command_on_bell     none
# bell_path           none
# linux_bell_theme    __custom
#: -------------------------------- }}}

#: Window layout ------------------ {{{
remember_window_position    yes
enabled_layouts             Tall,Fat,Splits,Stack
window_padding_width        6
confirm_os_window_close     0
#: -------------------------------- }}}

#: Tab bar ------------------------ {{{
tab_bar_style               powerline
tab_powerline_style         angled
# tab_bar_filter
tab_activity_symbol         *
tab_title_max_length        30
tab_title_template          "{bell_symbol}{activity_symbol}{title}"
active_tab_title_template   "{fmt.fg.green}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"
#: -------------------------------- }}}

#: Color scheme ------------------- {{{
background_opacity    0.9
background_blur       1
#: -------------------------------- }}}

#: Keyboard shortcuts ------------- {{{
kitty_mod   alt

#: Clipboard {{{
map ctrl+shift+c    copy_to_clipboard
map ctrl+shift+v    paste_from_clipboard
map kitty_mod+c     paste_from_selection
#: }}}

#: Scrolling {{{
map kitty_mod+shift+up      scroll_line_up
map kitty_mod+shift+down    scroll_line_down
#: }}}

#: Window management {{{
map kitty_mod+j             next_window
map kitty_mod+k             previous_window
map kitty_mod+shift+j       move_window_forward
map kitty_mod+shift+k       move_window_backward
map kitty_mod+shift+enter   move_window_to_top
map kitty_mod+;             focus_visible_window
map kitty_mod+shift+;       swap_with_window
#: }}}

#: Tab management {{{
map kitty_mod+t         new_tab
map kitty_mod+l         next_tab
map kitty_mod+h         previous_tab
map ctrl+tab            next_tab
map ctrl+shift+tab      previous_tab
map kitty_mod+shift+l   move_tab_forward
map kitty_mod+shift+h   move_tab_backward
map kitty_mod+shift+t   set_tab_title
#: }}}

#: Layout management {{{
map kitty_mod+space   next_layout
#: }}}
#: -------------------------------- }}}
