#? Config file for btop v.1.4.6


##* GENERAL *##

save_config_on_exit = false
background_update = false

#* theme under themes/
color_theme = "catppuccin-mocha"

#* false for transparency
theme_background = false

#* "h,j,k,l,g,G" keys for directional control
#* conflict keys: 'h:help' 'k:kill' -- access thru SHIFT
vim_keys = true

#* available: "cpu mem net proc" and "gpu0" to "gpu5"
shown_boxes = "cpu mem net proc"

#* graph symbol
graph_symbol = "braille"
graph_symbol_net = "block"

#* Define presets for the layout of the boxes. Preset 0 is always all boxes shown with default settings. Max 9 presets.
#* Format: "box_name:P:G,box_name:P:G" P=(0 or 1) for alternate positions, G=graph symbol to use for box.
#* Use whitespace " " as separator between different presets.
#* Example: "cpu:0:default,mem:0:tty,proc:1:default cpu:0:braille,proc:0:tty"
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"


##* PROC *##

proc_gradient = false
proc_mem_bytes = false
proc_left = false


##* CPU *##

cpu_bottom = false
freq_mode = "average"


##* MEM *##

mem_below_net = true
show_disks = true

#* graphs instead of meters
mem_graphs = false
