[input]
prepend_keymap = [
  { on = "<Esc>", run  = "close", desc = "Cancel input immediately" },
  { on = "<C-q>", run = "escape",   desc = "Exit visual mode, clear selection, or cancel search" }
]

[mgr]
prepend_keymap = [
  { on = "!", run  = 'shell "$SHELL" --block', desc = "Open $SHELL here", for  = "unix" },
  { on  = "q", run = "plugin confirm-quit", desc = "Confirm quit on multiple tabs" },
  { on  = "y", run = [ "shell -- echo %s | xclip -i -selection clipboard -t text/uri-list", "yank" ], desc = "Copy to system clipboard" },
  { on = [ "g", "r" ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to root work directory" },

  # Parent navigation
  { on  = "K", run = "plugin parent-arrow -1", desc = "Go up in parent navigation" },
  { on  = "J", run = "plugin parent-arrow 1", desc = "Go down in parent navigation" },

  # Smart function
  { on = [ "t", "t" ],  run  = "plugin smart-tab",      desc = "Create a tab and enter the hovered directory" },
  { on = [ "t", "s" ],  run = "plugin smart-switch 1",  desc = "Switch or create tab 2" },
  { on = "l",           run = "plugin smart-enter",     desc = "Enter the child directory, or open the file" },
  { on = "F",           run = "plugin smart-filter",    desc = "Smart filter" },
  { on = "P",           run  = "plugin smart-paste",    desc = "Paste into the hovered directory or CWD" },

  # Toggle pane
  { on   = [ "t", "n" ], run  = "plugin toggle-pane min-parent", desc = "Show or hide the preview pane", },
  { on   = [ "t", "m" ], run  = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },

  # Toggle metadata
  { on = "<F9>", run = "plugin mediainfo -- toggle-metadata", desc = "Toggle media preview metadata" },

  # Lazygit
  { on   = [ "g", "i" ], run  = "plugin lazygit", desc = "run lazygit" },

  # Compress
  { on   = [ "C", "a", "a" ], run  = "plugin compress",       desc = "Archive selected files" },
  { on   = [ "C", "a", "p" ], run  = "plugin compress -p",    desc = "Archive selected files (password)" },
  { on   = [ "C", "a", "h" ], run  = "plugin compress -ph",   desc = "Archive selected files (password+header)" },
  { on   = [ "C", "a", "l" ], run  = "plugin compress -l",    desc = "Archive selected files (compression level)" },
  { on   = [ "C", "a", "u" ], run  = "plugin compress -phl",  desc = "Archive selected files (password+header+level)" },
  # with ouch
  { on = [ "C", "o", "o" ], run = "plugin ouch",     desc = "Compress with ouch" },
  { on = [ "C", "o", "t" ], run = "plugin ouch tar", desc = "Compress with ouch" },

  # Mount
  { on  = "M", run = "plugin mount -- mount", desc = "Mount disk" },

  # Sudo
  { on = ["R", "p", "p"], run = "plugin sudo -- paste",                 desc = "sudo paste" },
  { on = ["R", "p"],      run = "plugin sudo -- paste --force",         desc = "sudo paste" },
  { on = ["R", "r"],      run = "plugin sudo -- rename",                desc = "sudo rename" },
  { on = ["R", "p", "l"], run = "plugin sudo -- link",                  desc = "sudo link" },
  { on = ["R", "p", "r"], run = "plugin sudo -- link --relative",       desc = "sudo link relative path" },
  { on = ["R", "p", "L"], run = "plugin sudo -- hardlink",              desc = "sudo hardlink" },
  { on = ["R", "a"],      run = "plugin sudo -- create",                desc = "sudo create" },
  { on = ["R", "d"],      run = "plugin sudo -- remove",                desc = "sudo trash" },
  { on = ["R", "D"],      run = "plugin sudo -- remove --permanently",  desc = "sudo delete" },
  { on = ["R", "m"],      run = "plugin sudo -- chmod",                 desc = "sudo chmod" },

  # Trash
  { on = [ "R","b" ],   run = "plugin recycle-bin",               desc = "Open Trash" },
  { on = [ "R", "t" ],  run = "plugin restore -- --interactive",  desc = "Restore deleted files/folders (Interactive)" },
]
