print_info() {
    info title
    info underline

    info "OS" distro
    info "Kernel" kernel
    info "Shell" shell
    info "Editor" editor
    info "Resolution" resolution
    info "DE" de
    # info "WM" wm
    # info "WM Theme" wm_theme
    info "Theme" theme
    info "Icons" icons
    info "Cursor" cursor
    info "Terminal" term
    # info "Terminal Font" term_font
    # info "CPU" cpu
    # info "GPU" gpu
    info "Memory" memory

    info "Disk" disk
    info "Battery" battery
    info "Font" font
    info "Song" song
    [[ "$player" ]] && prin "Music Player" "$player"

    info cols
}

title_fqdn="on"
kernel_shorthand="off"
distro_shorthand="on"
os_arch="off"
uptime_shorthand="off"

gtk_shorthand="on"
song_format="%title% - %artist%"
song_shorthand="off"
separator=":"
gap=1

block_range=(0 7)
block_width=5
col_offset="auto"

image_backend="ascii"
image_source="auto"
image_loop="off"
crop_mode="fill"
crop_offset="center"
image_size="auto"
catimg_size="2"
